name: Build and Package

on:
    push:
        tags:
            - "v*.*" # Trigger on version tags like v1.0, v2.1, etc.
    workflow_dispatch: # Allow manual triggering from GitHub Actions UI

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                go-version: [1.20]
                include:
                    - os: ubuntu-latest
                      goos: linux
                      goarch: amd64
                      archive: tar.gz
                    - os: macos-latest
                      goos: darwin
                      goarch: amd64
                      archive: tar.gz
                    - os: ubuntu-latest
                      goos: freebsd
                      goarch: amd64
                      archive: tar.gz
                    - os: windows-latest
                      goos: windows
                      goarch: amd64
                      archive: zip

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: ${{ matrix.go-version }}

            - name: Install dependencies
              run: go mod download

            - name: Build
              env:
                  GOOS: ${{ matrix.goos }}
                  GOARCH: ${{ matrix.goarch }}
              run: |
                  APP_NAME="cfddns"
                  VERSION=${GITHUB_REF#refs/tags/}
                  OUTPUT_NAME="${APP_NAME}_${VERSION}_${GOOS}_${GOARCH}"

                  if [ "$GOOS" == "windows" ]; then
                    BINARY_NAME="${APP_NAME}.exe"
                  else
                    BINARY_NAME="$APP_NAME"
                  fi

                  mkdir -p build/$OUTPUT_NAME
                  go build -o build/$OUTPUT_NAME/$BINARY_NAME main.go

                  # Package the binary
                  cd build/$OUTPUT_NAME
                  if [ "${{ matrix.archive }}" == "zip" ]; then
                    zip ../${OUTPUT_NAME}.zip $BINARY_NAME
                  else
                    tar -czf ../${OUTPUT_NAME}.tar.gz $BINARY_NAME
                  fi
                  cd ../..
                  rm -rf build/$OUTPUT_NAME

            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with:
                  name: ${{ matrix.goos }}-${{ matrix.goarch }}
                  path: |
                      build/*.tar.gz
                      build/*.zip
